name: 'Coral Proto Visualizer'
description: 'Visualize .proto file dependencies from gRPC/Connect projects'
author: 'daisuke8000'

branding:
  icon: 'git-branch'
  color: 'purple'

inputs:
  proto-path:
    description: 'Path to proto files directory'
    required: false
    default: 'proto'
  buf-config:
    description: 'Path to buf.yaml configuration file (relative to proto-path)'
    required: false
    default: ''
  comment-on-pr:
    description: 'Post analysis and diff as PR comment (true/false)'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token for PR comments'
    required: false
    default: ${{ github.token }}
  generate-pages:
    description: 'Generate static HTML for GitHub Pages (true/false)'
    required: false
    default: 'false'

outputs:
  json-path:
    description: 'Path to the generated JSON file'
    value: ${{ steps.generate.outputs.json-path }}
  html-path:
    description: 'Path to the generated HTML directory (if generate-pages is true)'
    value: ${{ steps.pages.outputs.html-path }}
  markdown-report:
    description: 'Detailed markdown report of proto dependencies'
    value: ${{ steps.generate.outputs.markdown-report }}
  diff-report:
    description: 'Diff report showing changes from base branch'
    value: ${{ steps.diff.outputs.diff-report }}

runs:
  using: 'composite'
  steps:
    - name: Setup buf CLI
      uses: bufbuild/buf-setup-action@v1
      with:
        github_token: ${{ inputs.github-token }}

    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: coral-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          coral-${{ runner.os }}-

    - name: Build Coral
      shell: bash
      working-directory: ${{ github.action_path }}
      run: cargo build --release

    - name: Generate proto graph
      id: generate
      shell: bash
      run: |
        mkdir -p "coral-output"
        cd "${{ inputs.proto-path }}"

        if [ -n "${{ inputs.buf-config }}" ]; then
          BUF_CMD="buf build --config ${{ inputs.buf-config }} -o -"
        else
          BUF_CMD="buf build -o -"
        fi

        eval "$BUF_CMD" | "${{ github.action_path }}/target/release/coral" --output json > \
          "${{ github.workspace }}/coral-output/graph.json"

        MARKDOWN=$(eval "$BUF_CMD" | "${{ github.action_path }}/target/release/coral" --output markdown)

        echo "json-path=coral-output/graph.json" >> $GITHUB_OUTPUT
        {
          echo "markdown-report<<EOF"
          echo "$MARKDOWN"
          echo "EOF"
        } >> $GITHUB_OUTPUT

    - name: Generate base branch data for diff
      if: inputs.comment-on-pr == 'true' && github.event_name == 'pull_request'
      id: diff
      shell: bash
      run: |
        HEAD_SHA=$(git rev-parse HEAD)

        git fetch origin "${{ github.base_ref }}" --depth=1
        git checkout "origin/${{ github.base_ref }}"

        cd "${{ inputs.proto-path }}"
        if [ -n "${{ inputs.buf-config }}" ]; then
          BUF_CMD="buf build --config ${{ inputs.buf-config }} -o -"
        else
          BUF_CMD="buf build -o -"
        fi

        eval "$BUF_CMD" | "${{ github.action_path }}/target/release/coral" --output json > \
          "${{ github.workspace }}/coral-output/base.json"

        git checkout "$HEAD_SHA"

        DIFF_REPORT=$("${{ github.action_path }}/target/release/coral" diff \
          "${{ github.workspace }}/coral-output/base.json" \
          "${{ github.workspace }}/coral-output/graph.json")

        {
          echo "diff-report<<EOF"
          echo "$DIFF_REPORT"
          echo "EOF"
        } >> $GITHUB_OUTPUT

    - name: Setup Node.js for UI build
      if: inputs.generate-pages == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Build UI for GitHub Pages
      if: inputs.generate-pages == 'true'
      shell: bash
      working-directory: ${{ github.action_path }}/ui
      run: |
        npm ci
        npm run build:static

    - name: Generate GitHub Pages
      if: inputs.generate-pages == 'true'
      id: pages
      shell: bash
      run: |
        cp -r "${{ github.action_path }}/ui/dist" "coral-output/html"
        cp "coral-output/graph.json" "coral-output/html/"
        echo "html-path=coral-output/html" >> $GITHUB_OUTPUT

    - name: Post PR Comment
      if: inputs.comment-on-pr == 'true' && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      env:
        MARKDOWN_REPORT: ${{ steps.generate.outputs.markdown-report }}
        DIFF_REPORT: ${{ steps.diff.outputs.diff-report }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const markdownReport = process.env.MARKDOWN_REPORT || '';
          const diffReport = process.env.DIFF_REPORT || '';

          let body = '';

          if (diffReport.trim()) {
            body += diffReport + '\n\n';
          }

          body += markdownReport;

          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const existingComment = comments.find(c =>
            c.user.type === 'Bot' && c.body.includes('Coral Proto Dependency Analysis')
          );

          if (existingComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existingComment.id,
              body: body.trim()
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body.trim()
            });
          }

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coral-${{ github.run_id }}
        path: coral-output
        retention-days: 1
        overwrite: true
